<?php
/*
  Plugin Name: Event Espresso - States/Provinces Pack: United Kingdom
  Plugin URI: http://www.eventespresso.com
  Description: The Event Espresso New Addon adds United Kingdom States/Provinces to Event Espresso 4
  Version: 1.0
  Author: Event Espresso
  Author URI: http://www.eventespresso.com
  Copyright 2014 Event Espresso (email : support@eventespresso.com)

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License, version 2, as
  published by the Free Software Foundation.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA02110-1301USA
*/

function ee_united_kingdom_states_provinces_activate() {
  $installed = get_option( 'ee_united_kingdom_states_provinces_added');
  
  if ($installed) return;

  global $wpdb;

  $sql = "INSERT INTO `" . $wpdb->prefix . "esp_state` (`CNT_ISO`, `STA_abbrev`, `STA_name`, `STA_active`) VALUES
    ('GB', 'GB-BKM', 'Buckinghamshire', 1),
    ('GB', 'GB-CAM', 'Cambridgeshire', 1),
    ('GB', 'GB-CMA', 'Cumbria', 1),
    ('GB', 'GB-DBY', 'Derbyshire', 1),
    ('GB', 'GB-DEV', 'Devon', 1),
    ('GB', 'GB-DOR', 'Dorset', 1),
    ('GB', 'GB-ESX', 'East Sussex', 1),
    ('GB', 'GB-ESS', 'Essex', 1),
    ('GB', 'GB-GLS', 'Gloucestershire', 1),
    ('GB', 'GB-HAM', 'Hampshire', 1),
    ('GB', 'GB-HRT', 'Hertfordshire', 1),
    ('GB', 'GB-KEN', 'Kent', 1),
    ('GB', 'GB-LAN', 'Lancashire', 1),
    ('GB', 'GB-LEC', 'Leicestershire', 1),
    ('GB', 'GB-LIN', 'Lincolnshire', 1),
    ('GB', 'GB-NFK', 'Norfolk', 1),
    ('GB', 'GB-NYK', 'North Yorkshire', 1),
    ('GB', 'GB-NTH', 'Northamptonshire', 1),
    ('GB', 'GB-NTT', 'Nottinghamshire', 1),
    ('GB', 'GB-OXF', 'Oxfordshire', 1),
    ('GB', 'GB-SOM', 'Somerset', 1),
    ('GB', 'GB-STS', 'Staffordshire', 1),
    ('GB', 'GB-SFK', 'Suffolk', 1),
    ('GB', 'GB-SRY', 'Surrey', 1),
    ('GB', 'GB-WAR', 'Warwickshire', 1),
    ('GB', 'GB-WSX', 'West Sussex', 1),
    ('GB', 'GB-WOR', 'Worcestershire', 1),
    ('GB', 'GB-BDG', 'Barking and Dagenham', 1),
    ('GB', 'GB-BNE', 'Barnet', 1),
    ('GB', 'GB-BEX', 'Bexley', 1),
    ('GB', 'GB-BRY', 'Brent', 1),
    ('GB', 'GB-CMD', 'Camden', 1),
    ('GB', 'GB-CRY', 'Croydon', 1),
    ('GB', 'GB-EAL', 'Ealing', 1),
    ('GB', 'GB-ENF', 'Enfield', 1),
    ('GB', 'GB-GRE', 'Greenwich', 1),
    ('GB', 'GB-HCK', 'Hackney', 1),
    ('GB', 'GB-HMF', 'Hammersmith and Fulham', 1),
    ('GB', 'GB-HRY', 'Haringey', 1),
    ('GB', 'GB-HRW', 'Harrow', 1),
    ('GB', 'GB-HAV', 'Havering', 1),
    ('GB', 'GB-HIL', 'Hillingdon', 1),
    ('GB', 'GB-HNS', 'Hounslow', 1),
    ('GB', 'GB-ISL', 'Islington', 1),
    ('GB', 'GB-KEC', 'Kensington and Chelsea', 1),
    ('GB', 'GB-KTT', 'Kingston upon Thames', 1),
    ('GB', 'GB-LBH', 'Lambeth', 1),
    ('GB', 'GB-LEW', 'Lewisham', 1),
    ('GB', 'GB-MRT', 'Merton', 1),
    ('GB', 'GB-NWM', 'Newham', 1),
    ('GB', 'GB-RDB', 'Redbridge', 1),
    ('GB', 'GB-RIC', 'Richmond upon Thames', 1),
    ('GB', 'GB-SWK', 'Southwark', 1),
    ('GB', 'GB-STN', 'Sutton', 1),
    ('GB', 'GB-TWH', 'Tower Hamlets', 1),
    ('GB', 'GB-WFT', 'Waltham Forest', 1),
    ('GB', 'GB-WND', 'Wandsworth', 1),
    ('GB', 'GB-WSM', 'Westminster', 1),            
    ('GB', 'GB-BNS', 'Barnsley', 1),
    ('GB', 'GB-BIR', 'Birmingham', 1),
    ('GB', 'GB-BOL', 'Bolton', 1),
    ('GB', 'GB-BRD', 'Bradford', 1),
    ('GB', 'GB-BUR', 'Bury', 1),
    ('GB', 'GB-CLD', 'Calderdale', 1),
    ('GB', 'GB-COV', 'Coventry', 1),
    ('GB', 'GB-DNC', 'Doncaster', 1),
    ('GB', 'GB-DUD', 'Dudley', 1),    
    ('GB', 'GB-GAT', 'Gateshead', 1),
    ('GB', 'GB-KIR', 'Kirklees', 1),
    ('GB', 'GB-KWL', 'Knowsley', 1),
    ('GB', 'GB-LDS', 'Leeds', 1),
    ('GB', 'GB-LIV', 'Liverpool', 1),
    ('GB', 'GB-MAN', 'Manchester', 1),
    ('GB', 'GB-NET', 'Newcastle upon Tyne', 1),
    ('GB', 'GB-NTY', 'North Tyneside', 1),
    ('GB', 'GB-OLD', 'Oldham', 1),
    ('GB', 'GB-RCH', 'Rochdale', 1),
    ('GB', 'GB-ROT', 'Rotherham', 1),
    ('GB', 'GB-SHN', 'St. Helens', 1),
    ('GB', 'GB-SLF', 'Salford', 1),
    ('GB', 'GB-SAW', 'Sandwell', 1),
    ('GB', 'GB-SFT', 'Sefton', 1),
    ('GB', 'GB-SHF', 'Sheffield', 1),
    ('GB', 'GB-SOL', 'Solihull', 1),
    ('GB', 'GB-STY', 'South Tyneside', 1),            
    ('GB', 'GB-SKP', 'Stockport', 1),
    ('GB', 'GB-SND', 'Sunderland', 1),
    ('GB', 'GB-TAM', 'Tameside', 1), 
    ('GB', 'GB-TRF', 'Trafford', 1),
    ('GB', 'GB-WKF', 'Wakefield', 1),
    ('GB', 'GB-WLL', 'Walsall', 1),
    ('GB', 'GB-WRL', 'Wirral', 1),
    ('GB', 'GB-WLV', 'Wolverhampton', 1),
    ('GB', 'GB-BAS', 'Wolverhampton', 1),
    ('GB', 'GB-BBD', 'Blackburn with Darwen', 1),
    ('GB', 'GB-BDF', 'Bedford', 1),
    ('GB', 'GB-BPL', 'Blackpool', 1),
    ('GB', 'GB-BMH', 'Bournemouth', 1),
    ('GB', 'GB-BRC', 'Bracknell Forest', 1),
    ('GB', 'GB-BNH', 'Brighton and Hove', 1),
    ('GB', 'GB-BST', 'Bristol, City of', 1),
    ('GB', 'GB-CBF', 'Central Bedfordshire', 1),            
    ('GB', 'GB-CHE', 'Cheshire East', 1),
    ('GB', 'GB-CHW', 'Cheshire West and Chester', 1),
    ('GB', 'GB-CON', 'Cornwall', 1),
    ('GB', 'GB-DAL', 'Darlington', 1),
    ('GB', 'GB-DER', 'Derby', 1),
    ('GB', 'GB-DUR', 'Durham, County', 1),
    ('GB', 'GB-ERY', 'East Riding of Yorkshire', 1),
    ('GB', 'GB-HAL', 'Halton', 1),
    ('GB', 'GB-HPL', 'Hartlepool', 1),
    ('GB', 'GB-HEF', 'Herefordshire', 1),
    ('GB', 'GB-IOW', 'Isle of Wight', 1),
    ('GB', 'GB-KHL', 'Kingston upon Hull', 1),
    ('GB', 'GB-LCE', 'Leicester', 1),
    ('GB', 'GB-LUT', 'Luton', 1),
    ('GB', 'GB-MDW', 'Medway', 1),
    ('GB', 'GB-MDB', 'Middlesbrough', 1),
    ('GB', 'GB-MIK', 'Milton Keynes', 1),
    ('GB', 'GB-NEL', 'North East Lincolnshire', 1),
    ('GB', 'GB-NLN', 'North Lincolnshire', 1),
    ('GB', 'GB-NSM', 'North Somerset', 1),
    ('GB', 'GB-NBL', 'Northumberland', 1),
    ('GB', 'GB-NGM', 'Nottingham', 1),
    ('GB', 'GB-PTE', 'Peterborough', 1),
    ('GB', 'GB-PLY', 'Plymouth', 1),
    ('GB', 'GB-POL', 'Poole', 1),
    ('GB', 'GB-POR', 'Portsmouth', 1),            
    ('GB', 'GB-RDG', 'Reading', 1),
    ('GB', 'GB-RCC', 'Redcar and Cleveland', 1),
    ('GB', 'GB-RUT', 'Rutland', 1),
    ('GB', 'GB-SHR', 'Shropshire', 1),
    ('GB', 'GB-SLG', 'Slough', 1), 
    ('GB', 'GB-SGC', 'South Gloucestershire', 1), 
    ('GB', 'GB-STH', 'Southampton', 1),
    ('GB', 'GB-SOS', 'Southend-on-Sea', 1),
    ('GB', 'GB-STT', 'Stockton-on-Tees', 1),
    ('GB', 'GB-STE', 'Stoke-on-Trent', 1),
    ('GB', 'GB-SWD', 'Swindon', 1),
    ('GB', 'GB-TFW', 'Telford and Wrekin', 1),
    ('GB', 'GB-THR', 'Thurrock', 1),
    ('GB', 'GB-TOB', 'Torbay', 1),
    ('GB', 'GB-WRT', 'Warrington', 1),
    ('GB', 'GB-WBK', 'West Berkshire', 1),
    ('GB', 'GB-WIL', 'Wiltshire', 1),
    ('GB', 'GB-WNM', 'Windsor and Maidenhead', 1),
    ('GB', 'GB-WOK', 'Wokingham', 1),
    ('GB', 'GB-YOR', 'York', 1),            
    ('GB', 'GB-LND', 'London, City of', 1),
    ('GB', 'GB-ANT', 'Antrim', 1),
    ('GB', 'GB-ARD', 'Ards', 1),
    ('GB', 'GB-ARM', 'Armagh', 1),
    ('GB', 'GB-BLA', 'Ballymena', 1),
    ('GB', 'GB-BLY', 'Ballymoney', 1),
    ('GB', 'GB-BNB', 'Banbridge', 1),
    ('GB', 'GB-BFS', 'Belfast', 1),
    ('GB', 'GB-CKF', 'Carrickfergus', 1),
    ('GB', 'GB-CSR', 'Castlereagh', 1),
    ('GB', 'GB-CLR', 'Coleraine', 1),
    ('GB', 'GB-CKT', 'Cookstown', 1),
    ('GB', 'GB-CGV', 'Craigavon', 1),
    ('GB', 'GB-DRY', 'Derry', 1),
    ('GB', 'GB-DOW', 'Down', 1),
    ('GB', 'GB-DGN', 'Dungannon and South Tyrone', 1),
    ('GB', 'GB-FER', 'Fermanagh', 1),
    ('GB', 'GB-LRN', 'Larne', 1),
    ('GB', 'GB-LMV', 'Limavady', 1),
    ('GB', 'GB-LSB', 'Lisburn', 1),
    ('GB', 'GB-MFT', 'Magherafelt', 1),
    ('GB', 'GB-MYL', 'Moyle', 1),
    ('GB', 'GB-NYM', 'Newry and Mourne District', 1),
    ('GB', 'GB-NTA', 'Newtownabbey', 1),
    ('GB', 'GB-NDN', 'North Down', 1),
    ('GB', 'GB-OMH', 'Omagh', 1),
    ('GB', 'GB-STB', 'Strabane', 1),
    ('GB', 'GB-ABE', 'Aberdeen City', 1),
    ('GB', 'GB-ABD', 'Aberdeenshire', 1),
    ('GB', 'GB-ANS', 'Angus', 1),
    ('GB', 'GB-AGB', 'Argyll and Bute', 1),
    ('GB', 'GB-CLK', 'Clackmannanshire', 1),
    ('GB', 'GB-DGY', 'Dumfries and Galloway', 1),
    ('GB', 'GB-DND', 'Dundee City', 1),            
    ('GB', 'GB-EAY', 'East Ayrshire', 1),
    ('GB', 'GB-EDU', 'East Dunbartonshire', 1),
    ('GB', 'GB-ELN', 'East Lothian', 1),
    ('GB', 'GB-ERW', 'East Renfrewshire', 1),
    ('GB', 'GB-EDH', 'Edinburgh, City of', 1),
    ('GB', 'GB-ELS', 'Eilean Siar', 1),
    ('GB', 'GB-FAL', 'Falkirk', 1),
    ('GB', 'GB-FIF', 'Fife', 1),
    ('GB', 'GB-GLG', 'Glasgow City', 1),
    ('GB', 'GB-HLD', 'Highland', 1),
    ('GB', 'GB-IVC', 'Inverclyde', 1),
    ('GB', 'GB-MLN', 'Midlothian', 1),
    ('GB', 'GB-MRY', 'Moray', 1),
    ('GB', 'GB-NAY', 'North Ayrshire', 1),
    ('GB', 'GB-NLK', 'North Lanarkshire', 1),
    ('GB', 'GB-ORK', 'Orkney Islands', 1),
    ('GB', 'GB-PKN', 'Perth and Kinross', 1),
    ('GB', 'GB-RFW', 'Renfrewshire', 1),
    ('GB', 'GB-SCB', 'Scottish Borders, The', 1),
    ('GB', 'GB-ZET', 'Shetland Islands', 1),
    ('GB', 'GB-SAY', 'South Ayrshire', 1),
    ('GB', 'GB-SLK', 'South Lanarkshire', 1),
    ('GB', 'GB-STG', 'Stirling', 1),
    ('GB', 'GB-WDU', 'West Dunbartonshire', 1),
    ('GB', 'GB-WLN', 'West Lothian', 1),    
    ('GB', 'GB-BGW', 'Blaenau Gwent', 1),            
    ('GB', 'GB-BGE', 'Bridgend', 1),
    ('GB', 'GB-CAY', 'Caerphilly', 1),
    ('GB', 'GB-CRF', 'Cardiff', 1),
    ('GB', 'GB-CMN', 'Carmarthenshire', 1),
    ('GB', 'GB-CGN', 'Ceredigion', 1),
    ('GB', 'GB-CWY', 'Conwy', 1),
    ('GB', 'GB-DEN', 'Denbighshire', 1),
    ('GB', 'GB-FLN', 'Flintshire', 1),
    ('GB', 'GB-GWN', 'Gwynedd', 1),
    ('GB', 'GB-AGY', 'Isle of Anglesey', 1),
    ('GB', 'GB-MTY', 'Merthyr Tydfil', 1),
    ('GB', 'GB-MON', 'Monmouthshire', 1),
    ('GB', 'GB-NTL', 'Neath Port Talbot', 1),
    ('GB', 'GB-NWP', 'Newport', 1),
    ('GB', 'GB-PEM', 'Pembrokeshire', 1),
    ('GB', 'GB-POW', 'Powys', 1),    
    ('GB', 'GB-RCT', 'Rhondda, Cynon, Taff', 1),            
    ('GB', 'GB-SWA', 'Swansea', 1),
    ('GB', 'GB-TOF', 'Torfaen', 1),
    ('GB', 'GB-VGL', 'Vale of Glamorgan, The', 1),    
    ('GB', 'GB-WRX', 'Wrexham', 1);";

  if ($wpdb->query($sql)){
    
    add_option( 'ee_united_kingdom_states_provinces_added', 1, '', 'no' );

  }

}
register_activation_hook( __FILE__, 'ee_united_kingdom_states_provinces_activate' );
